[uwsgi]
http = :9090
; socket = 0.0.0.0:9000
master = True
vhost = true
processes = 6
threads = 2
chdir = /data/django/Experiment-Tracking-App/experiment-app/
wsgi-file = experiment_app/wsgi.py
module=experiment_app.wsgi:application
vacuum = true
max-requests=100
buffer-size = 30000
static-map = /static=/data/django/Experiment-Tracking-App/experiment_app/static
harakiri = 3600
http-timeout = 3600
socket-timeout = 3600